# Generated by Django 4.0.6 on 2022-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=300)),
                ('languages', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='homepage/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
